version: '3.5'

services:
  composer-playground:
    container_name: composer-playground
    build:
      context: ./docker/composer-playground
    command: composer-playground -p 3002
    ports:
      - 3002:3002
    volumes:
      - ~/.composer:/home/composer/.composer

  composer-rest-server:
    container_name: composer-rest-server
    image: siphtor/composer-rest-server:latest
    build:
      context: ./docker/composer-rest-server
    ports:
      - 3001:3001
    volumes:
      - ~/.composer:/home/composer/.composer

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

networks:
  default:
    driver: bridge
    name: siphtor_dev

